mongod_conf: '/etc/mongod.conf'

mongod_pem: '/etc/ssl/mongodb.pem'
mongod_cafile: '/etc/ssl/mongodbca.pem'
mongod_client_pem: '/etc/ssl/client.pem'
mongod_lib: '/var/lib/mongo'

mongod_kmp_client_pem: '/etc/ssl/mongodb_kmip_client.pem'
mongod_kmp_cafile: '/etc/ssl/mongodb_kmip_ca.pem'

mongod_auditlog: '/var/lib/mongo/auditLog.bson'
saslauthd: '/etc/sysconfig/saslauthd'

mongod_hostname: 'MONGODB'

is_docker: 'true'
mongo_use_pki: 'true'
mongo_use_ldap: 'false'
mongo_use_saslauthd: 'false'

mongodb_packages_used: [
  'mongodb-org-tools-4.0.5-1.el7.x86_64',
  'mongodb-org-server-4.0.5-1.el7.x86_64',
  'mongodb-org-shell-4.0.5-1.el7.x86_64',
  'mongodb-org-4.0.5-1.el7.x86_64',
  'mongodb-org-mongos-4.0.5-1.el7.x86_64']

user: 'mongoadmin'
password: 'mongoadmin'

admin_db_users: ["mongodb_admin"]
config_db_users: ["config_admin"]
myUserAdmin_allowed_role: ['[ 
  { "role" : "userAdminAnyDatabase", "db" : "admin" } 
  ] }']

mongoadmin_allowed_role: ['[ { 
  "role" : "userAdminAnyDatabase", 
  "db" : "admin" 
  } ] }']
appAdmin_allowed_role: ['[
   { "role" : "readWrite", "db" : "config" }, 
   { "role" : "clusterAdmin", "db" : "admin" } 
   ] }']
accountAdmin01_allowed_role: ['[ 
  { "role" : "clusterAdmin", "db" : "admin" }, 
  { "role" : "readAnyDatabase", "db" : "admin" }, 
  { "role" : "readWrite", "db" : "config" } 
  ] }
  ']
